import jsPDF from "jspdf";
import type { ScanResult } from "./scanEngine";

export function generatePDFReport(result: ScanResult) {
  const doc = new jsPDF();
  const w = doc.internal.pageSize.getWidth();
  let y = 20;

  const addLine = (text: string, size = 10, bold = false) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", bold ? "bold" : "normal");
    const lines = doc.splitTextToSize(text, w - 40);
    if (y + lines.length * (size * 0.5) > 270) {
      doc.addPage();
      y = 20;
    }
    doc.text(lines, 20, y);
    y += lines.length * (size * 0.45) + 4;
  };

  const addSection = (title: string) => {
    y += 4;
    doc.setDrawColor(0, 200, 200);
    doc.line(20, y, w - 20, y);
    y += 8;
    addLine(title, 14, true);
  };

  // Header
  doc.setTextColor(0, 200, 200);
  addLine("SECUREBOT — AI SECURITY INTELLIGENCE REPORT", 18, true);
  doc.setTextColor(60, 60, 60);
  addLine(`Domain: ${result.domain}`, 11);
  addLine(`Generated: ${new Date(result.timestamp).toLocaleString()}`, 10);
  y += 4;

  // Executive Summary
  addSection("EXECUTIVE SUMMARY");
  doc.setTextColor(40, 40, 40);
  const scoreLabel = result.threatScore >= 90 ? "SECURE" : result.threatScore >= 70 ? "MODERATE RISK" : "HIGH RISK";
  addLine(`Behavioral Threat Score: ${result.threatScore}/100 (${scoreLabel})`, 11, true);
  addLine(`AI Confidence: ${result.aiConfidence}%`);
  addLine(`The automated AI analysis identified ${result.suspiciousIPs} suspicious IP addresses and ${result.anomalousTraffic}% anomalous traffic patterns. Bot probability was assessed at ${result.botProbability}% with a data exfiltration likelihood of ${result.exfiltrationLikelihood}%.`);

  // Behavioral Findings
  addSection("BEHAVIORAL ANALYSIS");
  addLine(`Anomalous Traffic: ${result.anomalousTraffic}%`);
  addLine(`Suspicious IP Activity: ${result.suspiciousIPs} sources`);
  addLine(`Bot Probability: ${result.botProbability}%`);
  addLine(`Data Exfiltration Likelihood: ${result.exfiltrationLikelihood}%`);
  addLine("Risk Categories:");
  result.riskHeatmap.forEach(r => addLine(`  • ${r.category}: ${r.score}/100`));

  // Zero-Day Results
  addSection("ZERO-DAY DETECTION");
  const zd = result.zeroDayResults;
  addLine(`Risk Classification: ${zd.riskClassification}`, 11, true);
  addLine(`Unknown Script Execution: ${zd.scriptExecutionDetected ? "DETECTED" : "Not detected"}`);
  addLine(`Payload Detonation: ${zd.payloadDetonated ? "DETONATED IN SANDBOX" : "No detonation"}`);
  addLine(`Exploit Similarity: ${zd.exploitSimilarity}%`);
  addLine(`Zero-Day Probability: ${zd.zeroDayProbability}%`);
  addLine(`CVE Similarity Match: ${zd.cveSimilarity}%`);
  addLine(`Behavioral Fingerprint: ${zd.behavioralFingerprint}`);

  // Automated Response
  addSection("AUTOMATED RESPONSE ACTIONS");
  const ra = result.responseActions;
  addLine(`Malicious IP Blocked: ${ra.blockedIP}`);
  addLine(`Suspicious Endpoint Isolated: ${ra.isolatedEndpoint}`);
  addLine(`Payload Neutralized: ${ra.payloadNeutralized ? "Yes" : "No"}`);
  addLine(`Firewall Rule Generated: ${ra.firewallRule}`);
  addLine(`Patch Recommendation: ${ra.patchRecommendation}`);

  // ML Models
  addSection("ENSEMBLE ML MODEL VERIFICATION");
  addLine(`Overall Model Confidence: ${result.aiConfidence}%`);
  addLine(`False Positive Rate: ${(100 - result.aiConfidence).toFixed(1)}%`);
  result.mlModels.forEach(m => addLine(`  • ${m.name}: ${m.confidence}% (${m.status})`));

  // Remediation
  addSection("RECOMMENDED REMEDIATIONS");
  addLine("1. Implement rate limiting on identified endpoints");
  addLine("2. Update WAF rules with generated firewall signatures");
  addLine("3. Rotate API keys for isolated endpoints");
  addLine("4. Apply recommended patches immediately");
  addLine("5. Enable enhanced logging on flagged IP ranges");
  addLine("6. Review and update CORS policies");

  // Footer
  y += 8;
  doc.setFontSize(8);
  doc.setTextColor(120, 120, 120);
  doc.text("This report was generated by SecureBot AI Security Platform. For informational purposes only.", 20, y);

  doc.save(`securebot-report-${result.domain.replace(/\./g, "-")}.pdf`);
}
